load("//tools/build_defs/oss:ig_json_parser_defs.bzl", "fb_java_library")

fb_java_library(
    name = "support",
    srcs = glob(["src/main/java/**/*.java"]),
    labels = ["supermodule:android/default/infra.ig_json_parser"],
    visibility = [
        "//fbandroid/libraries/ig-json-parser/...",
    ],
    deps = [
        "//xplat/nuclide/fb-JavaLib/org.json:json",
    ],
    exported_deps = [
        "//xplat/nuclide/fb-JavaLib/org.json:json",
    ],
)
