load("//tools/build_defs/android:robolectric4_test.bzl", "robolectric4_test")
load("//tools/build_defs/oss:ig_json_parser_defs.bzl", "fb_java_library", "fb_native")

fb_java_library(
    name = "processor-lib",
    srcs = glob(["src/main/java/**/*.java"]),
    labels = ["supermodule:android/default/infra.ig_json_parser"],
    resources = glob(["src/main/resources/**"]),
    resources_root = "src/main/resources/",
    tests = ["//fbandroid/libraries/ig-json-parser/processor:processor-test"],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//fbandroid/libraries/ig-json-parser/common:common",
        "//fbandroid/libraries/ig-json-parser/javawriter:javawriter",
        "//fbandroid/libraries/ig-json-parser/util:util",
        "//fbandroid/third-party/java/jackson:core",
        "//fbandroid/third-party/java/jsr-305:jsr-305",
        "//third-party/java/commons-lang3:commons-lang3",
    ],
)

fb_native.java_annotation_processor(
    name = "processor",
    labels = ["supermodule:android/default/infra.ig_json_parser"],
    processor_class = "com.instagram.common.json.annotation.processor.JsonAnnotationProcessor",
    supports_abi_generation_from_source = True,
    visibility = [
        "PUBLIC",
    ],
    deps = [
        ":processor-lib",
    ],
)

robolectric4_test(
    name = "processor-test",
    srcs = glob([
        "**/test/**/*.kt",
        "**/test/**/*.java",
    ]),
    labels = ["supermodule:android/default/infra.ig_json_parser"],
    language = "KOTLIN",
    deps = [
        "fbsource//third-party/kotlin:kotlin",
        "fbsource//third-party/kotlin:kotlin-stdlib",
        "//fbandroid/libraries/ig-json-parser:runtime",
        "//fbandroid/libraries/ig-json-parser/processor/support:support",
        "//fbandroid/libraries/ig-json-parser/processor/testuut:testuut",
        "//fbandroid/libraries/ig-json-parser/processor/testuut/dependent:dependent",
        "//fbandroid/libraries/ig-json-parser/processor/testuut/kotlin:kotlin",
        "//fbandroid/libraries/ig-json-parser/processor/testuut/nobodies:nobodies",
        "//fbandroid/libraries/ig-json-parser/processor/testuut/noserializers:noserializers",
        "//fbandroid/libraries/ig-json-parser/processor/testuut/parent:parent",
        "//fbandroid/third-party/java/guava:guava",
        "//fbandroid/third-party/java/jackson:core",
        "//fbandroid/third-party/java/junit:junit",
    ],
)
