load(
    "//tools/build_defs/oss:ig_json_parser_defs.bzl",
    "fb_java_library",
)

fb_java_library(
    name = "common",
    srcs = glob(["src/main/java/**/*.java"]),
    labels = ["supermodule:android/default/infra.ig_json_parser"],
    required_for_source_only_abi = True,
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//fbandroid/third-party/java/jackson:core",
    ],
)
